name: Tests

on:
  push:
    branches: [ "main", "production" ]
  pull_request:
    branches: [ "main", "production" ]

jobs:
  tests:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v5

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.4'

    - name: Copy .env
      run: cp .env.example .env

    - name: Install Dependencies
      run: composer install -v --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Generate key
      run: php artisan key:generate

    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Create Database
      run: |
        touch database/database.sqlite
        php artisan migrate --force

    - name: Install Dependencies
      run: npm ci

    - name: Build assets
      run: npm run build

    - name: Execute tests
      run: php artisan test

    - name: Check code style
      run: ./vendor/bin/pint --test

    # No frontend linting for now.
    #- name: Lint assets
    #  run: npm run lint

    # No frontend tests for now.
    # - name: Execute tests (Unit and Feature tests) via Jest
    #   run: npm run test
